apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-  # Name of this Workflow
spec:
  entrypoint: whalesay22        # it means which template we will use first. it their are many then it will use this defined first.
  templates:
  - name: whalesay22            # Defining the "whalesay" template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"] # This template runs "cowsay" in the "whalesay" image with arguments "hello world" 