apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-secret-environment-
spec:
  entrypoint: dag-template-22
  arguments:
    parameters:
      - name: message1
        value: Task 1 is executed
      - name: message2
        value: Task 2 is executed
  templates:
    - name: dag-template-22
      inputs:
        parameters:
          - name: message1
          - name: message2
      dag:
        tasks:
          - name: Task1
            arguments:
              parameters: [{name: text, value: "{{inputs.parameters.message1}}"}]
            template: task-template-22
          - name: Task2
            arguments:
              parameters: [{name: text, value: "{{inputs.parameters.message2}}"}]
            template: task-template-22
          - name: Task3
            template: task-secret-environment-22
            dependencies: [Task1]

    - name: task-template-22
      inputs:
        parameters:
          - name: text
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          p = "{{inputs.parameters.text}}"
          print(p)

    - name: task-secret-environment-22
      script:
        image: python:3.8-slim
        command: [python]
        source: |
          import os
          print(os.environment['TEST_PASSWORD'])
        env:
          - name: TEST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: test-secret
                key: test-password
