apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  generateName: wf-dag-cron-workflow-
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: "Allow"               # <-- we can put  "Allow", "Forbid", "Replace"
  startingDeadlineSeconds: 70
  workflowSpec:                        #<-- here we are defining the workflow will execute under this Cronjob
    entrypoint: dag-template-22
    templates:
      - name: dag-template-22
        dag:
          tasks:
            - name: Task1
              template: task-template-22
            - name: Task2
              template: task-template-22
              dependencies: [Task1]
            - name: Task3
              template: task-template-22
              dependencies: [Task1]
            - name: Task4
              template: task-template-22
              dependencies: [Task2, Task3]

      - name: task-template-22
        script:
          image: python:3.8-slim
          command: [python]
          source: |
            print("task executed --- ww2222 ")
